name: Ebise Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing Deployments
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.HOST_PORT }}
          script: |
            git stash
            git pull
            git stash pop
            # git stash apply
